[package]
name = "shook_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
log = "0.4.17"
serde = { version = "1.0.143", features = ["derive"] }
